In [1]:
import numpy as np
import pandas as pd

In [2]:
mobility_DE = pd.read_csv("google_mobility_DE.csv")

states = mobility_DE["sub_region_1"].unique()[1:]

In [3]:
state_data = mobility_DE[mobility_DE["sub_region_1"] == states[0]]
mobility_data_column = "residential_percent_change_from_baseline"

In [8]:
# make new df with states as columns and dates as rows
mobility_data = pd.DataFrame(columns=states, index=state_data["date"])

# fill in with mobility data from mobility_data_column
# by iterating over mobility_DE
for state in states:
    state_data = mobility_DE[mobility_DE["sub_region_1"] == state]
    mobility_data[state] = state_data[mobility_data_column].values

# cut off after index date "2021-12-31"
mobility_data = mobility_data.loc[: "2021-12-31"]

# save to csv
mobility_data.to_csv("mobility_data_by_Bundesland.csv")

# Get relevant data subset

Manually download the Global Google Mobility Report csv into the same folder first!

In [2]:
google_mobility = pd.read_csv("Global_Mobility_Report.csv")
google_mobility.head()

C:\Users\iftek\AppData\Local\Temp\ipykernel_19836\4101118996.py:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  google_mobility = pd.read_csv("Global_Mobility_Report.csv")

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0

In [3]:
# filter for country_region = Germany
google_mobility_DE = google_mobility[google_mobility['country_region'] == 'Germany']

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
3756359,DE,Germany,NaN,NaN,NaN,NaN,NaN,ChIJa76xwh5ymkcRW-WRjmtd6HU,2020-02-15,6.0,1.0,45.0,10.0,0.0,-1.0
3756360,DE,Germany,NaN,NaN,NaN,NaN,NaN,ChIJa76xwh5ymkcRW-WRjmtd6HU,2020-02-16,7.0,10.0,9.0,6.0,-1.0,0.0
3756361,DE,Germany,NaN,NaN,NaN,NaN,NaN,ChIJa76xwh5ymkcRW-WRjmtd6HU,2020-02-17,2.0,2.0,7.0,1.0,-2.0,0.0
3756362,DE,Germany,NaN,NaN,NaN,NaN,NaN,ChIJa76xwh5ymkcRW-WRjmtd6HU,2020-02-18,2.0,2.0,10.0,1.0,-1.0,1.0
3756363,DE,Germany,NaN,NaN,NaN,NaN,NaN,ChIJa76xwh5ymkcRW-WRjmtd6HU,2020-02-19,3.0,0.0,6.0,-1.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772912,DE,Germany,Thuringia,NaN,NaN,DE-TH,NaN,ChIJk_E62n8PpEcR0Hk0dMGOIAE,2022-10-11,-2.0,18.0,91.0,15.0,-4.0,3.0
3772913,DE,Germany,Thuringia,NaN,NaN,DE-TH,NaN,ChIJk_E62n8PpEcR0Hk0dMGOIAE,2022-10-12,5.0,18.0,101.0,21.0,-3.0,2.0
3772914,DE,Germany,Thuringia,NaN,NaN,DE-TH,NaN,ChIJk_E62n8PpEcR0Hk0dMGOIAE,2022-10-13,2.0,19.0,73.0,17.0,-3.0,3.0
3772915,DE,Germany,Thuringia,NaN,NaN,DE-TH,NaN,ChIJk_E62n8PpEcR0Hk0dMGOIAE,2022-10-14,-3.0,18.0,60.0,17.0,-5.0,3.0
3772916,DE,Germany,Thuringia,NaN,NaN,DE-TH,NaN,ChIJk_E62n8PpEcR0Hk0dMGOIAE,2022-10-15,-4.0,13.0,76.0,36.0,7.0,0.0

In [4]:
# save to csv
google_mobility_DE.to_csv('google_mobility_DE.csv', index=False)